spring:
  application:
    name: social-manager
  jackson:
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      accept_empty_string_as_null_object: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true
    url: jdbc:h2:file:~/test
    username: dev
    password: dev
    driverClassName: org.h2.Driver
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  http:
    multipart:
      max-request-size: 5MB
      max-file-size: 12MB
  devtools:
    restart:
      enabled: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  signing-key: SocialManagerDprApp
  api: /api/jwt
  enable: true

assm:
  app:
    jwtSecret: jwtAssmSecretKey
    jwtExpiration: 86400
